### ISSUE TITLE
Todo-List (1) [CLOSED]

### ISSUE THREAD

**Issue by NicoAICP** [Ultimate-WiiU-VC-Injectors/CSharp-Injectors#1]
- [x] Downloading without batch

- [x] packing without batch

- [x] editing xml without batch + generating random 4 digit hex string for id and pdc
